### PR TITLE
telegram: Add support for topics.

### PR DESCRIPTION
**Pull request by fishinthecalculator**

### CODE REVIEW

**Review by chobeat — APPROVED** [review]
cool, but why?

**Comment by fishinthecalculator** [comment]
> cool, but why?

just in case lol, it seemed not a big burden in terms of maintainability and it does not impact current operations. we can discuss it better if you'd like

**Comment by chobeat** [comment]
no, it's ok, I just can't imagine the output looking good

**Comment by fishinthecalculator** [comment]
> no, it's ok, I just can't imagine the output looking good

i tested simple publication with a supergroup with topics and it looked normal. i didn't test extensively (things like recaps or notifications) but i believe if it becomes necessary we can track this in a dedicated issue

**Pull request merged**
