### PR TITLE
add dry run

### PR DESCRIPTION
**Pull request by chobeat**

### CODE REVIEW

**Comment by chobeat** [comment]
@fishinthecalculator sorry, this was supposed to be opened before the other PR and reviewed separately. Address it before the other one

**Comment by chobeat** [comment]
about the CommandConfig: I want to keep separate the Command configurations and the normal configurations. The CommandConfig shouldn't be defined at Dynaconf level because it comes from the CLI and it's unnecessarily awkward to set it at Dynaconf level. On top of that, every command might have different parameters and this separation is more future-proof than throwing everything into the same config

**Review by fishinthecalculator — COMMENTED** [review]
Isn't this the same branch as #169 ? We already merged it with https://github.com/Tech-Workers-Coalition-Italia/mobilizon-reshare/commit/9d71ef36b98f42c8a9445570c43762c5b383bb2e . Just to be sure, otherwise we can merge this.

**Comment by chobeat** [comment]
I'm confused because there's a big diff but yeah, it was already merged, in theory... Maybe it's the squash that did something weird

**Comment by fishinthecalculator** [comment]
I simulated the merge of this PR on my personal fork and it actually adds no commits, so it should be safe to merge https://github.com/fishinthecalculator/mobilizon-reshare/commits/master . I'd try and if we find any anomaly we can revert the commit

**Pull request merged**
